version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: phpunit/phpunit
    versions:
    - "< 7.4, > 7.3.2"
  - dependency-name: phpunit/phpunit
    versions:
    - "< 7.6, > 7.5.0"
  - dependency-name: phpunit/phpunit
    versions:
    - ">= 8.a, < 9"
