language: php

php:
  - '5.4'
  - '5.6'
  - '7.0'
  - '7.1'

before_script:
  - composer install

script:
  - php -S localhost:8000 tests/server.php &
  - composer test

notifications:
  - email: false
