language: php

php:
  - '7.1'
  - '7.2'

before_script:
  - composer install

script:
  - php -S localhost:8000 tests/server.php &
  - composer test

after_script:
  - vendor/bin/test-reporter

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

notifications:
  - email: false
